// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArOUyqFArFsLTYw3_JufPAm2-ruSVNPWY',
    appId: '1:215842570107:web:7488a5903047896a2f47de',
    messagingSenderId: '215842570107',
    projectId: 'skillcycle-07',
    authDomain: 'skillcycle-07.firebaseapp.com',
    storageBucket: 'skillcycle-07.firebasestorage.app',
    measurementId: 'G-MGV9J48VN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK1movts_7qfk8SpQvxXjSOzZ7yRWkV7U',
    appId: '1:215842570107:android:e6a96e198b0c94522f47de',
    messagingSenderId: '215842570107',
    projectId: 'skillcycle-07',
    storageBucket: 'skillcycle-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1Ly21Lpv1BnaJ381aIKW9vfftkf8Loo',
    appId: '1:215842570107:ios:01d4e04ac759650e2f47de',
    messagingSenderId: '215842570107',
    projectId: 'skillcycle-07',
    storageBucket: 'skillcycle-07.firebasestorage.app',
    iosBundleId: 'com.deek.app.skill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1Ly21Lpv1BnaJ381aIKW9vfftkf8Loo',
    appId: '1:215842570107:ios:01d4e04ac759650e2f47de',
    messagingSenderId: '215842570107',
    projectId: 'skillcycle-07',
    storageBucket: 'skillcycle-07.firebasestorage.app',
    iosBundleId: 'com.deek.app.skill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArOUyqFArFsLTYw3_JufPAm2-ruSVNPWY',
    appId: '1:215842570107:web:9c097530e4662c422f47de',
    messagingSenderId: '215842570107',
    projectId: 'skillcycle-07',
    authDomain: 'skillcycle-07.firebaseapp.com',
    storageBucket: 'skillcycle-07.firebasestorage.app',
    measurementId: 'G-XNMYTBC60E',
  );
}
